### ISSUE TITLE
Get the current Assembly Command

### ISSUE THREAD

**Issue by SebastianZug** [ponty/pysimavr#11]
Hi ponty,

I want to run a step by step analysis of my elf file and have some questions:
- The output of avr.pc does not correspond with the real PC? I received 0, 2, 4, 6, 8 ... but according to 
   0:	0c 94 34 00 	jmp	0x68	; 0x68 <__ctors_end>
  the order should be 0, 0x68, 0,x70, etc.
- how can I cast avr.sreg from a python program. Its a swig object ... and I have no idea :-)

Thanks for your help!

Sebastian

**Comment by ponty** [comment]
**sreg** is an int array. I should check how swig handles arrays.

**Comment by SebastianZug** [comment]
And what about the value of avr.pc? Its behaviour is strange, it looks more like a permanent incrementation than the address of the next opcode? I walked through the code but I cannot identify any problem :-(

**Comment by ponty** [comment]
Please check the latest version for SREG.

```python
avr=Avr()
print avr.sreg
```

**Comment by SebastianZug** [comment]
Yes, it works. Very nice. I started to run some additional examples an will deliver them soon.

Thanks a lot!

Sebastian
